- name: 'configuration playbook'
  hosts: instance
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_host_key_checking: false
    ansible_stdout_callback: yaml

  pre_tasks:
    pre_tasks:
    - name: 'wait 600 seconds for target connection to become reachable/usable.'
      wait_for_connection:
        timeout: 600
        
    - name: 'Install python for Ansible'
      become: true
      apt:
        name: python3
        update_cache: yes

  roles:
    - deploy-backend