apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  namespace: todo-api
  labels:
    app: todo-api
spec:
  selector:
    matchLabels:
      app: todo-api
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: kennedyuche/todo-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_SERVER
              value: postgresdb-0.postgres-db.todo-api.svc
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          livenessProbe:
            httpGet:
              path: /api/v1/status
              port: 5000
            initialDelaySeconds: 100
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: 5000
            initialDelaySeconds: 100
          resources:
            limits:
              cpu: 64m
              memory: 512Mi