apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: todo-api
spec:
  selector:
    app: postgres-stateful-db
  clusterIP: None
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432